#!/usr/bin/env python3
# RSA factoring challenge
import sys
import os
if len(sys.argv) != 2:
	print("Usage:", sys.argv[0], "file")
	exit(1)
if not os.path.isfile(sys.argv[1]):
	print(sys.argv[0]+":", "File", sys.argv[1], "not found.")
	exit(1)
with open(sys.argv[1]) as f:
	for to_factor in f:
		found = 0
		with open("primes_million_1") as primes:
			for line in primes:
				line_nums = [int(n) for n in line.split()]
				for prime in line_nums:
					if int(to_factor) % prime == 0:
						print("{}={}*{}".format(int(to_factor), int(int(to_factor)/prime), prime))
						found = 1
						break
				if found:
					break
