#!/usr/bin/env python3
# RSA factoring challenge
import sys
import os
import math
if len(sys.argv) != 2:
    print("Usage:", sys.argv[0], "file")
    exit(1)
if not os.path.isfile(sys.argv[1]):
    print(sys.argv[0]+":", "File", sys.argv[1], "not found.")
    exit(1)
with open(sys.argv[1]) as f:
    for to_factor in f:
        to_factor = int(to_factor)
        if not to_factor % 2:
            print("{}={}*2".format(to_factor, to_factor // 2))
            continue
        i = 3
        end=math.sqrt(to_factor)
        while i <= end:
            if not to_factor % i:
                print("{}={}*{}".format(to_factor, to_factor // i, i))
                break
            i += 2
        if i > end:
            print("{}={}*{}".format(to_factor, to_factor, 1))
